"""Add is_temporary field to Graph

Revision ID: 3db0f842053a
Revises: 91c0ff1bf28a
Create Date: 2025-02-24 19:07:58.649896

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3db0f842053a'
down_revision = '91c0ff1bf28a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('graphs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_temporary', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('graphs', schema=None) as batch_op:
        batch_op.drop_column('is_temporary')

    # ### end Alembic commands ###
