"""Add tracked_metrics field to Graph

Revision ID: 4a5b6c7d8e9f
Revises: 3db0f842053a
Create Date: 2025-06-01 15:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a5b6c7d8e9f'
down_revision = '3db0f842053a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('graphs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tracked_metrics', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('graphs', schema=None) as batch_op:
        batch_op.drop_column('tracked_metrics')

    # ### end Alembic commands ### 